"""Constant for set of keywords."""

# Add keyword string to below set, preferably in alphabetical order.
# We are adding this manually for now. Add to a txt file, If/when we automate this.
# Important: Please use lower case.

KEYWORDS = {
    "alert",
    "autoscale",
    "cluster",
    "config",
    "configmap",
    "console",
    "container",
    "crd",
    "deploy",
    "deployment",
    "image",
    "imagepullpolicy",
    "imagepullsecret",
    "infra",
    "ingress",
    "k8s",
    "kubernetes",
    "log",
    "master",
    "namespace",
    "network",
    "node",
    "oc",
    "ocp",
    "openshift",
    "operator",
    "pod",
    "podconfig",
    "poddisruptionbudgets",
    "podsecurity",
    "policy",
    "project",
    "quay",
    "replica",
    "replicaset",
    "secret",
    "service",
    "virtualization",
    "worker",
    "yaml",
}
