apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-n6d64
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: builder-dockercfg-n6d64
    creationTimestamp: "2024-10-08T12:47:03Z"
    name: builder
    namespace: openshift-lightspeed
    resourceVersion: "127125"
    uid: 2135ea3e-c40d-4df2-8b67-ebb742b751b2
  secrets:
  - name: builder-dockercfg-n6d64
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-zvx9z
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: default-dockercfg-zvx9z
    creationTimestamp: "2024-10-08T12:47:03Z"
    name: default
    namespace: openshift-lightspeed
    resourceVersion: "127123"
    uid: 1ee8e5c4-600c-463a-b784-eafb5bd8d575
  secrets:
  - name: default-dockercfg-zvx9z
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-29v8m
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: deployer-dockercfg-29v8m
    creationTimestamp: "2024-10-08T12:47:03Z"
    name: deployer
    namespace: openshift-lightspeed
    resourceVersion: "127124"
    uid: e2b2de7b-e9b4-482b-9245-8d71034ea491
  secrets:
  - name: deployer-dockercfg-29v8m
- apiVersion: v1
  imagePullSecrets:
  - name: lightspeed-app-server-dockercfg-drjnm
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: lightspeed-app-server-dockercfg-drjnm
    creationTimestamp: "2024-10-08T12:55:48Z"
    name: lightspeed-app-server
    namespace: openshift-lightspeed
    ownerReferences:
    - apiVersion: ols.openshift.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: OLSConfig
      name: cluster
      uid: 702ba649-c360-408e-ba46-848fdb15da63
    resourceVersion: "130587"
    uid: 9d2af9e2-4774-4c46-b084-d0d7829b2b0a
  secrets:
  - name: lightspeed-app-server-dockercfg-drjnm
- apiVersion: v1
  imagePullSecrets:
  - name: lightspeed-operator-controller-manager-dockercfg-cpwpj
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: lightspeed-operator-controller-manager-dockercfg-cpwpj
    creationTimestamp: "2024-10-08T12:48:27Z"
    labels:
      olm.managed: "true"
      operators.coreos.com/lightspeed-operator.openshift-lightspeed: ""
    name: lightspeed-operator-controller-manager
    namespace: openshift-lightspeed
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: ClusterServiceVersion
      name: lightspeed-operator.v0.1.7
      uid: aa79ebdf-4d83-4599-a01b-77f5f06ab092
    resourceVersion: "127715"
    uid: b9fe69b0-655b-4c83-9e8d-56539015ba13
  secrets:
  - name: lightspeed-operator-controller-manager-dockercfg-cpwpj
- apiVersion: v1
  imagePullSecrets:
  - name: metrics-test-user-dockercfg-hlhz7
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: metrics-test-user-dockercfg-hlhz7
    creationTimestamp: "2024-10-08T12:55:40Z"
    name: metrics-test-user
    namespace: openshift-lightspeed
    resourceVersion: "130490"
    uid: a4d15991-5ea6-47d7-ac3c-d7cdd40b57c6
  secrets:
  - name: metrics-test-user-dockercfg-hlhz7
- apiVersion: v1
  imagePullSecrets:
  - name: test-user-dockercfg-fwstj
  kind: ServiceAccount
  metadata:
    annotations:
      openshift.io/internal-registry-pull-secret-ref: test-user-dockercfg-fwstj
    creationTimestamp: "2024-10-08T12:55:39Z"
    name: test-user
    namespace: openshift-lightspeed
    resourceVersion: "130479"
    uid: 8b054039-d5f4-49fa-9299-97cef2ce41ff
  secrets:
  - name: test-user-dockercfg-fwstj
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
