#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["packaging>=24.1"]
# ///
r"""Generate requirements.overrides.txt for Konflux dual-index compiles.

Runs `uv pip compile` with PyPI + RHOAI and `--emit-index-annotation`. If
`requirements.overrides.txt` (or ``-o``) already exists, it is passed as ``--override`` for that
compile so the annotated graph matches Konflux (same locked stack). Pins for packages declared
with extras in ``[tool.uv] constraint-dependencies`` are written as ``name[extras]==…``.
After writing, runs the same dual-index compile with ``--override`` and exits non-zero if the
project does not resolve (adjust ``[project]`` deps).

  uv run --script scripts/generate_requirements_overrides.py -o requirements.overrides.txt

Use `--compiled-input` to pass an existing annotated file instead of running uv.

The RHOAI simple API often returns HTTP 403 without auth; use
`--header 'Authorization: Bearer <token>'` (offline token from console.redhat.com).
"""

from __future__ import annotations

import argparse
import html.parser
import os
import re
import subprocess
import sys
import tempfile
import tomllib
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urljoin, urlparse

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name, parse_sdist_filename, parse_wheel_filename
from packaging.version import InvalidVersion, Version

DEFAULT_RHOAI = "https://console.redhat.com/api/pypi/public-rhai/rhoai/3.3/cpu-ubi9/simple/"
DEFAULT_PYPI = "https://pypi.org/simple/"
PYPI_SIMPLE_MARKER = "pypi.org/simple"

HEADER = (
    "# Selective pins for `uv pip compile --override` with dual indexes and\n"
    "# `--index-strategy unsafe-best-match` (steer PyPI-resolved packages to RHOAI versions).\n"
    "# Generated by scripts/generate_requirements_overrides.py\n"
    f"# RHOAI: {DEFAULT_RHOAI}\n"
)

USER_AGENT = (
    "ols-generate-requirements-overrides/1.0 "
    "(compatible; +https://github.com/openshift/lightspeed-service)"
)

RHOAI_403_HINT = (
    "\nThe RHOAI simple API returned HTTP 403. It usually requires Red Hat "
    "authentication (same as browser access to console.redhat.com).\n"
    "Options:\n"
    "  export RHOAI_INDEX_BEARER_TOKEN=<offline_token>\n"
    "  uv run --script scripts/generate_requirements_overrides.py -o requirements.overrides.txt\n"
    "or:\n"
    "  uv run --script scripts/generate_requirements_overrides.py \\\n"
    "    --header 'Authorization: Bearer <OFFLINE_TOKEN>' -o requirements.overrides.txt\n"
)


@dataclass
class LinkParser(html.parser.HTMLParser):
    hrefs: list[str]

    def __init__(self) -> None:
        super().__init__()
        self.hrefs = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag != "a":
            return
        for name, value in attrs:
            if name == "href" and value:
                self.hrefs.append(value)
                return


def _basename_from_href(href: str) -> str | None:
    path = urlparse(href).path
    name = path.rsplit("/", 1)[-1]
    if not name or name in (".", ".."):
        return None
    return name.split("#", 1)[0]


def _version_from_artifact_filename(filename: str) -> Version | None:
    lowered = filename.lower()
    try:
        if lowered.endswith(".whl"):
            _n, ver, _b, _t = parse_wheel_filename(filename)
            return ver
        if lowered.endswith(".tar.gz") or lowered.endswith(".zip"):
            _n, ver = parse_sdist_filename(filename)
            return ver
    except (ValueError, InvalidVersion):
        return None
    return None


def fetch_versions_for_project(
    index_url: str,
    project_name: str,
    opener: urllib.request.OpenerDirector,
) -> list[Version]:
    normalized = canonicalize_name(project_name)
    base = index_url if index_url.endswith("/") else index_url + "/"
    url = urljoin(base, f"{normalized}/")
    req = urllib.request.Request(url, method="GET")
    try:
        with opener.open(req, timeout=120) as resp:
            body = resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return []
        if e.code == 403:
            raise SystemExit(
                f"HTTP 403 Forbidden fetching {url}\n{RHOAI_403_HINT}",
            ) from e
        raise
    parser = LinkParser()
    parser.feed(body)
    versions: set[Version] = set()
    for href in parser.hrefs:
        base_name = _basename_from_href(href)
        if not base_name:
            continue
        ver = _version_from_artifact_filename(base_name)
        if ver is not None:
            versions.add(ver)
    return sorted(versions)


def _is_pypi_simple_index(url: str) -> bool:
    u = url.rstrip("/").lower()
    return PYPI_SIMPLE_MARKER in u


def _normalize_rhoai_base(url: str) -> str:
    return url if url.endswith("/") else url + "/"


def _pin_version_from_requirement(req: Requirement) -> Version | None:
    for spec in req.specifier:
        if spec.operator in ("==", "==="):
            try:
                return Version(spec.version)
            except InvalidVersion:
                return None
    return None


def _constraint_dependency_extras(pyproject: Path) -> dict[str, frozenset[str]]:
    """Map canonical package name -> extras declared in [tool.uv] constraint-dependencies."""
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    tool_uv = (data.get("tool") or {}).get("uv") or {}
    raw = tool_uv.get("constraint-dependencies")
    if not raw or not isinstance(raw, list):
        return {}
    merged: dict[str, set[str]] = {}
    for line in raw:
        if not isinstance(line, str) or not line.strip():
            continue
        try:
            req = Requirement(line.strip())
        except ValueError:
            continue
        key = canonicalize_name(req.name)
        if not req.extras:
            continue
        merged.setdefault(key, set()).update(req.extras)
    return {k: frozenset(v) for k, v in merged.items()}


def _format_override_pin(
    name: str,
    chosen: Version,
    extras_by_pkg: dict[str, frozenset[str]],
) -> str:
    extras = extras_by_pkg.get(canonicalize_name(name))
    if extras:
        extra_str = ",".join(sorted(extras))
        return f"{name}[{extra_str}]=={chosen}"
    return f"{name}=={chosen}"


def parse_pypi_sourced_pins(compiled_text: str, rhoai_index_url: str) -> list[tuple[str, Version]]:
    """Return (name, resolved_version) for packages whose # from line is PyPI simple."""
    rhoai_norm = _normalize_rhoai_base(rhoai_index_url).rstrip("/").lower()
    lines = compiled_text.splitlines()
    out: list[tuple[str, Version]] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if line[0] in " \t" or "==" not in line:
            i += 1
            continue
        pkg_line = line.strip()
        i += 1
        index_url: str | None = None
        while i < len(lines):
            cont = lines[i]
            if (
                cont
                and cont[0] not in " \t"
                and not cont.lstrip().startswith("#")
                and "==" in cont
            ):
                break
            if "# from " in cont or cont.strip().startswith("# from"):
                m = re.search(r"#\s*from\s+(\S+)", cont)
                if m:
                    index_url = m.group(1).strip().rstrip("/")
            i += 1
        if index_url is None:
            continue
        idx_lower = index_url.lower()
        if rhoai_norm and idx_lower.startswith(rhoai_norm):
            continue
        if not _is_pypi_simple_index(index_url):
            continue
        try:
            req = Requirement(pkg_line.split(";", 1)[0].strip())
        except (ValueError, InvalidVersion):
            continue
        ver = _pin_version_from_requirement(req)
        if ver is None:
            continue
        out.append((req.name, ver))
    return out


def run_uv_compile(
    pyproject: Path,
    rhoai_index: str,
    pypi_index: str,
    python_version: str,
    extras: list[str],
    extra_uv_args: list[str],
    seed_override: Path | None,
) -> str:
    out = Path(tempfile.mkstemp(suffix=".txt", prefix="uv-annotate-")[1])
    cmd = [
        "uv",
        "pip",
        "compile",
        str(pyproject),
        "-o",
        str(out),
        "--index-strategy",
        "unsafe-best-match",
        "--python-version",
        python_version,
        "--universal",
        "--refresh",
        "--index",
        _normalize_rhoai_base(rhoai_index),
        "--default-index",
        _normalize_rhoai_base(pypi_index),
        "--emit-index-annotation",
        "--no-sources",
    ]
    if seed_override is not None and seed_override.is_file():
        cmd.extend(["--override", str(seed_override)])
    for e in extras:
        cmd.extend(["--extra", e])
    cmd.extend(extra_uv_args)
    proc = subprocess.run(cmd, capture_output=True, text=True)
    try:
        if proc.returncode != 0:
            sys.stderr.write(proc.stderr or proc.stdout or "")
            raise SystemExit(proc.returncode or 1)
        return out.read_text(encoding="utf-8")
    finally:
        out.unlink(missing_ok=True)


def verify_override_resolution(
    pyproject: Path,
    rhoai_index: str,
    pypi_index: str,
    python_version: str,
    override_path: Path,
    extras: list[str],
    extra_uv_args: list[str],
) -> None:
    """Fail if pyproject cannot be resolved with the generated override file."""
    out = Path(tempfile.mkstemp(suffix=".txt", prefix="uv-verify-")[1])
    cmd = [
        "uv",
        "pip",
        "compile",
        str(pyproject),
        "-o",
        str(out),
        "--override",
        str(override_path),
        "--index-strategy",
        "unsafe-best-match",
        "--python-version",
        python_version,
        "--universal",
        "--index",
        _normalize_rhoai_base(rhoai_index),
        "--default-index",
        _normalize_rhoai_base(pypi_index),
        "--no-sources",
    ]
    for e in extras:
        cmd.extend(["--extra", e])
    cmd.extend(extra_uv_args)
    proc = subprocess.run(cmd, capture_output=True, text=True)
    out.unlink(missing_ok=True)
    if proc.returncode != 0:
        sys.stderr.write(
            "Override pins do not resolve with the project (dual-index compile failed).\n"
            "Adjust [project] dependencies and regenerate.\n\n",
        )
        sys.stderr.write(proc.stderr or proc.stdout or "")
        raise SystemExit(proc.returncode or 1)


def build_opener(headers: list[str]) -> urllib.request.OpenerDirector:
    class InjectHeaders(urllib.request.BaseHandler):
        def http_request(self, req: urllib.request.Request) -> urllib.request.Request:
            if req.get_header("User-agent") is None:
                req.add_header("User-Agent", USER_AGENT)
            for h in headers:
                name, _, value = h.partition(":")
                req.add_header(name.strip(), value.strip())
            return req

        https_request = http_request

    return urllib.request.build_opener(InjectHeaders())


def main() -> None:
    p = argparse.ArgumentParser(
        description="Generate selective requirements.overrides.txt from annotated uv compile.",
    )
    p.add_argument("--pyproject", type=Path, default=Path("pyproject.toml"))
    p.add_argument(
        "--compiled-input",
        type=Path,
        help="Annotated compile output (skip running uv if set)",
    )
    p.add_argument("--rhoai-index", default=DEFAULT_RHOAI)
    p.add_argument("--pypi-index", default=DEFAULT_PYPI)
    p.add_argument("--python-version", default="3.12")
    p.add_argument("--extra", action="append", default=[], metavar="NAME")
    p.add_argument("-o", "--output", type=Path, default=Path("requirements.overrides.txt"))
    p.add_argument("--no-header-comment", action="store_true")
    p.add_argument(
        "--header",
        action="append",
        default=[],
        metavar="NAME: VALUE",
        help="HTTP headers for RHOAI requests (repeatable). "
        "If unset, reads $RHOAI_INDEX_BEARER_TOKEN as Authorization: Bearer when no "
        "Authorization header is passed.",
    )
    p.add_argument("--dry-run", action="store_true")
    p.add_argument(
        "--no-seed-override",
        action="store_true",
        help="Do not pass the existing output file as --override for the annotation compile.",
    )
    p.add_argument(
        "uv_extra",
        nargs="*",
        help="Extra args forwarded to uv pip compile when generating input",
    )
    args = p.parse_args()

    if args.compiled_input:
        text = args.compiled_input.read_text(encoding="utf-8")
    else:
        if not args.pyproject.is_file():
            raise SystemExit(f"Not found: {args.pyproject}")
        seed_override: Path | None = None
        if not args.no_seed_override and args.output.is_file():
            seed_override = args.output
        text = run_uv_compile(
            args.pyproject,
            args.rhoai_index,
            args.pypi_index,
            args.python_version,
            args.extra,
            args.uv_extra,
            seed_override,
        )

    pypi_pins = parse_pypi_sourced_pins(text, args.rhoai_index)
    if not pypi_pins:
        raise SystemExit(
            "No PyPI-sourced pins found in annotated input. "
            "Use an uv compile output with --emit-index-annotation.",
        )

    headers = list(args.header)
    if not any(h.partition(":")[0].strip().lower() == "authorization" for h in headers):
        token = os.environ.get("RHOAI_INDEX_BEARER_TOKEN", "").strip()
        if token:
            headers.append(f"Authorization: Bearer {token}")

    opener = build_opener(headers)
    extras_by_pkg = _constraint_dependency_extras(args.pyproject)
    lines_out: list[str] = []
    warnings: list[str] = []

    for name, want in sorted(pypi_pins, key=lambda t: canonicalize_name(t[0])):
        avail = fetch_versions_for_project(args.rhoai_index, name, opener)
        if not avail:
            warnings.append(f"{name}: not on RHOAI index, skip")
            continue
        if want in avail:
            chosen = want
        else:
            not_newer = [v for v in avail if v <= want]
            if not_newer:
                chosen = max(not_newer)
                warnings.append(
                    f"{name}: PyPI had {want}, RHOAI best <= that is {chosen} (no exact match)",
                )
            else:
                warnings.append(
                    f"{name}: PyPI had {want}, RHOAI has no version <= {want}; skip "
                    f"(avoids picking e.g. kubernetes newer than pyproject allows)",
                )
                continue
        lines_out.append(_format_override_pin(name, chosen, extras_by_pkg))

    for w in warnings:
        print(w, file=sys.stderr)

    body = "\n".join(lines_out) + "\n"
    if not args.no_header_comment:
        body = HEADER + "\n" + body

    if args.dry_run:
        sys.stdout.write(body)
        return

    args.output.write_text(body, encoding="utf-8")
    if not args.compiled_input:
        verify_override_resolution(
            args.pyproject,
            args.rhoai_index,
            args.pypi_index,
            args.python_version,
            args.output,
            args.extra,
            args.uv_extra,
        )

    print(
        f"Wrote {args.output} ({len(lines_out)} pins from {len(pypi_pins)} PyPI-sourced packages)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
