#!/bin/bash

# Script to split requirements by index source
# Packages from pypi.org go to requirements.source.txt
# Packages from console.redhat.com go to requirements.wheel.txt

set -ex

RAW_REQ_FILE="requirements.no_hashes.txt"
SOURCE_FILE="requirements.source.txt"
WHEEL_FILE="requirements.wheel.txt"
SOURCE_HASH_FILE="requirements.hashes.source.txt"
WHEEL_HASH_FILE="requirements.hashes.wheel.txt"
BUILD_FILE="requirements-build.txt"
RHOAI_INDEX_URL="https://console.redhat.com/api/pypi/public-rhai/rhoai/3.3/cpu-ubi9/simple/"

# extra wheels to be included in the wheel list,
# often come from build-time dependencies, or source are not available on pypi.org
EXTRA_WHEELS="uv,uv-build,pip,maturin,griffe,griffecli,griffelib,rank_bm25"
# packages to exclude from the wheel list
NO_WHEEL_PACKAGES="markupsafe"
# packages to exclude from pybuild-deps (causes RecursionError due to circular build dep chain)
SKIP_PYBUILD_PACKAGES="banks"

# filtered source file for pybuild-deps to avoid RecursionError
SOURCE_FILE_FOR_BUILD=$(mktemp)

cleanup() {
	# remove intermediate files
	rm -f "$RAW_REQ_FILE" "$WHEEL_FILE" "$SOURCE_FILE" "$SOURCE_FILE_FOR_BUILD"
}

trap cleanup EXIT INT TERM

# Generate requirements list from pyproject.toml from both indexes
uv pip compile pyproject.toml -o "$RAW_REQ_FILE" \
	--python-platform x86_64-unknown-linux-gnu \
	--python-version 3.12 \
	--refresh \
	--index ${RHOAI_INDEX_URL} \
	--default-index https://pypi.org/simple/ \
	--index-strategy unsafe-best-match \
	--emit-index-annotation \
	--no-sources \
	--override requirements.overrides.txt

# Initialize output files
echo "# Packages from pypi.org" >"$SOURCE_FILE"
echo "# This file was autogenerated by $(basename -- "$0")" >>"$SOURCE_FILE"
echo "# Packages from ${RHOAI_INDEX_URL}" >"$WHEEL_FILE"
echo "# This file was autogenerated by $(basename -- "$0")" >>"$WHEEL_FILE"
echo "--index-url ${RHOAI_INDEX_URL}" >>"$WHEEL_FILE"

current_package=""

while IFS= read -r line || [[ -n "$line" ]]; do
	# Check if this is a package line (starts with a letter/digit, not whitespace or #)
	if [[ "$line" =~ ^[a-zA-Z0-9] ]]; then
		current_package="$line"
		package_name="${current_package%%==*}"
	# Check if this is a "# from" annotation line
	elif [[ "$line" =~ ^[[:space:]]*#[[:space:]]*from[[:space:]]+(.*) ]]; then
		index_url="${BASH_REMATCH[1]}"

		if [[ -n "$current_package" ]]; then
			force_no_wheel=0
			for no_wheel_pkg in ${NO_WHEEL_PACKAGES//,/ }; do
				[[ "$package_name" == "$no_wheel_pkg" ]] && force_no_wheel=1
				break
			done

			if [[ "$index_url" == "https://pypi.org/simple/" ]]; then
				echo "$current_package" >>"$SOURCE_FILE"
			elif [[ "$force_no_wheel" -eq 1 ]]; then
				echo "$current_package" >>"$SOURCE_FILE"
			elif [[ "$index_url" == "${RHOAI_INDEX_URL}" ]]; then
				echo "$current_package" >>"$WHEEL_FILE"
			fi
			current_package=""
		fi
	fi
done <"$RAW_REQ_FILE"

# replace the list of binary packages in konflux pipeline configuration
# only the package names, not the versions, delimited by commas
wheel_packages=$(grep -v "^[#-]" "$WHEEL_FILE" | sed 's/==.*//' | tr '\n' ',' | sed 's/,$//')

echo "Packages from pypi.org written to: $SOURCE_FILE ($(wc -l <"$SOURCE_FILE") packages)"
echo "Packages from console.redhat.com written to: $WHEEL_FILE ($(wc -l <"$WHEEL_FILE") packages)"

uv pip compile "$WHEEL_FILE" --refresh --generate-hashes --index-url "${RHOAI_INDEX_URL}" --python-version 3.12 --emit-index-url --no-deps --no-annotate --universal >"$WHEEL_HASH_FILE"
uv pip compile "$SOURCE_FILE" --refresh --generate-hashes --python-version 3.12 --emit-index-url --no-deps --no-annotate >"$SOURCE_HASH_FILE"

# remove extra wheels from the build dependencies
for pkg in ${EXTRA_WHEELS//,/ }; do
	pkg=$(echo "$pkg" | tr -d '[:space:]')
	[[ -n "$pkg" ]] && sed -i "/^${pkg}[=<>!~]/d" "$SOURCE_FILE"
done

# Exclude packages that cause RecursionError in pybuild-deps (circular build dep chain)
{
	grep -v "^[#-]" "$SOURCE_FILE" | while IFS= read -r line; do
		[[ -z "$line" ]] && continue
		pkg_name="${line%%[=<>!~]*}"
		skip=0
		for skip_pkg in ${SKIP_PYBUILD_PACKAGES//,/ }; do
			skip_pkg=$(echo "$skip_pkg" | tr -d '[:space:]')
			[[ -n "$skip_pkg" ]] && [[ "$pkg_name" == "$skip_pkg" ]] && skip=1 && break
		done
		[[ $skip -eq 0 ]] && echo "$line"
	done
	# Add hatchling when banks is skipped (banks uses hatchling as build backend)
	if [[ "$SKIP_PYBUILD_PACKAGES" == *"banks"* ]] && grep -q "^banks" "$SOURCE_FILE"; then
		echo "hatchling==1.29.0"
	fi
} >>"$SOURCE_FILE_FOR_BUILD"
uv run pybuild-deps compile --output-file="$BUILD_FILE" "$SOURCE_FILE_FOR_BUILD"

# Exclude packages that are already included in the wheel list, to avoid hash conflicts
for pkg in ${wheel_packages//,/ }; do
	pkg=$(echo "$pkg" | tr -d '[:space:]')
	[[ -n "$pkg" ]] && sed -i "/^${pkg}[=<>!~]/d" "$BUILD_FILE"
done

# append extra wheels to the list
wheel_packages="$wheel_packages,$EXTRA_WHEELS"
sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' .tekton/lightspeed-service-pull-request.yaml
sed -i 's/"packages": "[^"]*"/"packages": "'"$wheel_packages"'"/' .tekton/lightspeed-service-push.yaml

echo "Done!"
echo "Packages from pypi.org written to: $SOURCE_HASH_FILE ($(wc -l <"$SOURCE_HASH_FILE") packages)"
echo "Packages from console.redhat.com written to: $WHEEL_HASH_FILE ($(wc -l <"$WHEEL_HASH_FILE") packages)"
echo "Build dependencies written to: $BUILD_FILE ($(wc -l <"$BUILD_FILE") packages)"
echo "Remember to commit $SOURCE_HASH_FILE, $WHEEL_HASH_FILE, $BUILD_FILE, pipeline configurations and push the changes"
