#!/bin/bash

load_vllm_model_profile() {
  case "${VLLM_MODEL_PROFILE:-llama-3.1-8b}" in
    llama-3.1-8b)
      VLLM_MODEL="meta-llama/Llama-3.1-8B-Instruct"
      VLLM_TOOL_CALL_PARSER="llama3_json"
      VLLM_CHAT_TEMPLATE_URL="https://raw.githubusercontent.com/vllm-project/vllm/main/examples/tool_chat_template_llama3.1_json.jinja"
      VLLM_CHAT_TEMPLATE_CONFIGMAP="vllm-chat-template"
      VLLM_CHAT_TEMPLATE_KEY="tool_chat_template_llama3.1_json.jinja"
      VLLM_GPU_COUNT="1"
      VLLM_TENSOR_PARALLEL_SIZE="1"
      VLLM_MAX_MODEL_LEN="35936"
      VLLM_GPU_MEMORY_UTILIZATION="0.9"
      VLLM_RUNTIME_CPU_REQUEST="4"
      VLLM_RUNTIME_CPU_LIMIT="6"
      VLLM_RUNTIME_MEMORY_REQUEST="16Gi"
      VLLM_RUNTIME_MEMORY_LIMIT="20Gi"
      VLLM_INFERENCE_SERVICE_CPU_REQUEST="2"
      VLLM_INFERENCE_SERVICE_CPU_LIMIT="4"
      VLLM_INFERENCE_SERVICE_MEMORY_REQUEST="16Gi"
      VLLM_INFERENCE_SERVICE_MEMORY_LIMIT="20Gi"
      ;;
    gemma-4-31b)
      VLLM_MODEL="google/gemma-4-31B-it"
      VLLM_TOOL_CALL_PARSER="gemma4"
      VLLM_CHAT_TEMPLATE_URL="https://huggingface.co/google/gemma-4-31B-it/raw/main/chat_template.jinja"
      VLLM_CHAT_TEMPLATE_CONFIGMAP="vllm-chat-template"
      VLLM_CHAT_TEMPLATE_KEY="gemma-4-chat-template.jinja"
      VLLM_GPU_COUNT="4"
      VLLM_TENSOR_PARALLEL_SIZE="4"
      VLLM_MAX_MODEL_LEN="16000"
      VLLM_GPU_MEMORY_UTILIZATION="0.9"
      VLLM_RUNTIME_CPU_REQUEST="32"
      VLLM_RUNTIME_CPU_LIMIT="40"
      VLLM_RUNTIME_MEMORY_REQUEST="128Gi"
      VLLM_RUNTIME_MEMORY_LIMIT="160Gi"
      VLLM_INFERENCE_SERVICE_CPU_REQUEST="32"
      VLLM_INFERENCE_SERVICE_CPU_LIMIT="40"
      VLLM_INFERENCE_SERVICE_MEMORY_REQUEST="128Gi"
      VLLM_INFERENCE_SERVICE_MEMORY_LIMIT="160Gi"
      ;;
    *)
      printf 'Unsupported VLLM model profile %q. Supported profiles: llama-3.1-8b, gemma-4-31b.\n' \
        "${VLLM_MODEL_PROFILE}" >&2
      return 1
      ;;
  esac

  export VLLM_MODEL VLLM_TOOL_CALL_PARSER VLLM_CHAT_TEMPLATE_URL
  export VLLM_CHAT_TEMPLATE_CONFIGMAP VLLM_CHAT_TEMPLATE_KEY VLLM_GPU_COUNT
  export VLLM_TENSOR_PARALLEL_SIZE VLLM_MAX_MODEL_LEN VLLM_GPU_MEMORY_UTILIZATION
  export VLLM_RUNTIME_CPU_REQUEST VLLM_RUNTIME_CPU_LIMIT VLLM_RUNTIME_MEMORY_REQUEST
  export VLLM_RUNTIME_MEMORY_LIMIT VLLM_INFERENCE_SERVICE_CPU_REQUEST
  export VLLM_INFERENCE_SERVICE_CPU_LIMIT VLLM_INFERENCE_SERVICE_MEMORY_REQUEST
  export VLLM_INFERENCE_SERVICE_MEMORY_LIMIT
}
